name: Deploy Blog

on:
  push:
    branches: 
      - master
      - gh-actions
      - gh-actions-test

jobs:
  deploy-blog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.3.4
      - name: Jekyll Actions
        uses: helaili/jekyll-action@2.0.4
        env: 
          JEKYLL_PAT:  ${{ secrets.JEKYLL_PAT }}